# fly.toml app configuration file generated for prisma-data-proxy on 2023-06-09T11:03:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prisma-data-proxy"
primary_region = "sin"

[build]
  image = "loxxo/aifactory-pdp:0.2.0"
[env]
  DATABASE_URL = "mysql://8jnr1hi4o1t9mwewo5cc:pscale_pw_eqsGlssuqfiCJUPBea8yRESIrQm46NVexUoBOxyLXoj@aws.connect.psdb.cloud/aifactory?sslaccept=stric"
  DATA_PROXY_API_KEY = "9exultCannot6"
  PORT = 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
