# fly.toml app configuration file generated for aifactory-quirrel on 2023-06-04T17:32:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aifactory-quirrel"
primary_region = "sin"

[build]
  image = "ghcr.io/quirrel-dev/quirrel:main"

[[services]]
  protocol = "tcp"
  internal_port = 9181

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
